### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by mebibou** [ayecue/mocha-prepare-promise#1]
When using this code:
```
const prepare = require('mocha-prepare-promise');
const mongoUnit = require('mongo-unit');

prepare(async () => {
  process.env.MONGODB_URL = await mongoUnit.start();
}, () => Promise.resolve());
```
(tried with and without the `() => Promise.resolve()` as second argument)

I get this error:
```
(node:7702) UnhandledPromiseRejectionWarning: TypeError: CreateListFromArrayLike called on non-object
    at wait.then ([...]/node_modules/mocha-prepare-promise/index.js:26:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ayecue** [comment]
@mebibou Thanks for reporting. With https://github.com/ayecue/mocha-prepare-promise/commit/b7706eef1b783e0a1fe177cc6664b7025cc1648a this issue should be fixed.
